#!/bin/bash

# Returns success only if we are certain we are active

CONFIG=/etc/nubis-config/active.sh

# Load up our current status
if [ -r $CONFIG ]; then
  . $CONFIG
else
  echo "Can't find our config: $CONFIG"
  exit 1
fi

if [ "$BUGZILLA_ACTIVE" == "1" ]; then
  exit 0
else
  exit 1
fi
