#!/bin/bash

CONFIG=/etc/nubis-config/bugzilla.sh

DATA=/data/bugzilla

# Load up $S3DataBucket
if [ -r $CONFIG ] ; then
  . $CONFIG
else
  echo "Can't find config in $CONFIG"
  exit 1
fi

S3_SYNC="aws s3 sync \
  --no-guess-mime-type \
  --sse \
  --exclude=mod_perl_preload \
  --exclude=webdot/ \
  $* \
"

if /usr/local/bin/bugzilla-active; then
  # Push
  $S3_SYNC "$DATA/" "s3://$S3DataBucket/"
else
  # Pull
  $S3_SYNC "s3://$S3DataBucket/" "$DATA/"
fi
