#!/bin/bash

CONFIG=/etc/nubis-config/active.sh
# Load up our current status
if [ -r $CONFIG ]; then
  . $CONFIG
else
  echo "Can't find our config: $CONFIG"
  exit 1
fi

# Services to stop/start
SERVICES="\
bugzilla-queue \
bugzilla-push \
"

if [ "$BUGZILLA_ACTIVE" == "1" ]; then
  echo "Starting Active services:"
  for s in $SERVICES; do
    service "$s" start
  done
else
  echo "Stopping Passive services:"
  for s in $SERVICES; do
    service "$s" stop
  done
fi
