#!/bin/bash

# Exit if anything fails
set -e

DISTS=/var/www/dists
if [ ! -d $DISTS ]; then
  mkdir $DISTS
fi

CPANM="cpanm --save-dists $DISTS"

# Force install, this is failing some tests
$CPANM --force --configure-timeout 300 Math::BigInt::Pari
$CPANM --force --configure-timeout 300 Math::BigInt::GMP

for pkg in \
   Math::Random::ISAAC \
   File::MimeInfo::Magic \
   Daemon::Generic \
   Crypt::OpenPGP \
   Crypt::SMIME \
   TheSchwartz \
   Any::URI::Escape \
   Chart::Base \
   HTTP::Lite \
   JSON::RPC \
   PatchReader \
   Authen::Radius \
   Template::Plugin::GD \
   Math::BigInt \
   ElasticSearch@0.68 \
   Test::Number::Delta \
   Math::Random::MT \
   Devel::StackTrace \
   Convert::Base32 \
   Auth::GoogleAuth \
   Net::SFTP \
   File::Copy::Recursive \
  ; do
  echo "Installing $pkg"
  $CPANM $pkg
done

tar -C $(dirname $DISTS) -zcvf $DISTS.tar.gz $(basename $DISTS)
rm -rf $DISTS
