#!/bin/bash

# Exit if anything fails
set -e

# Verbose
set -x

echo "Monkey patching for SES issue https://bugzilla.mozilla.org/show_bug.cgi?id=1259942"
curl 'https://bug1259942.bmoattachments.org/attachment.cgi?id=8775692' | ( cd /var/www/bugzilla; patch -p1 )

exit 0
