#!/bin/bash

SRC=/var/www/bugzilla-params
DST=/var/www/bugzilla/data/params

echo "Updating params from $SRC to $DST"

cp -a $SRC $DST

service httpd restart

/usr/local/bin/bugzilla-run-if-active service bugzilla-queue restart
/usr/local/bin/bugzilla-run-if-active service bugzilla-push restart
