#!/bin/bash

CONFIG=/etc/nubis-config/active.sh
# Load up our current status
if [ -r $CONFIG ]; then
  . $CONFIG
else
  echo "Can't find our config: $CONFIG"
  exit 1
fi

if [ "$BUGZILLA_ACTIVE" == "1" ]; then
  exec "$@"
else
  echo "Skipping, we are not active"
  exit 1
fi

