#!/bin/bash

# Amazon Linux issue
export PATH=/usr/local/bin:$PATH

# Redirect stdout and stderr to the logfile and the console
exec > >(tee /var/log/bugzilla-update.log)
exec 2>&1

# Source the consul connection details from the metadata api
eval `curl -fq http://169.254.169.254/latest/user-data`

consul lock $NUBIS_STACK/$NUBIS_ENVIRONMENT/checksetup \
    perl -I/var/www/bugzilla /var/www/bugzilla/checksetup.pl /var/www/bugzilla/answers.txt

# Restart dependent services
service httpd restart

/usr/local/bin/bugzilla-run-if-active service bugzilla-queue restart
/usr/local/bin/bugzilla-run-if-active service bugzilla-push restart
