#!/bin/bash

set -x

sudo gem install bundler --no-ri --no-rdoc
sudo gem install io-console --no-ri --no-rdoc
sudo gem install json --no-ri --no-rdoc

cd /tmp/tests
bundle install --path=vendor
bundle exec rake spec

STATUS=$?

# Cleanup after ourselves
cd /tmp
rm -rf /tmp/tests

exit $STATUS
